### ISSUE TITLE
support for strfnames/strnames

### ISSUE THREAD

**Issue by dcegielka** [sabotage-linux/netbsd-curses#34] opened 2018-11-26 17:52 UTC
[libtermkey](https://github.com/o11c/libtermkey) requires [strfnames](https://github.com/o11c/libtermkey/blob/master/driver-ti.c#L186)/[strnames](https://github.com/o11c/libtermkey/blob/master/driver-ti.c#L201), which are not currently available in netbsd-curses. The patch was created thanks to the [help](https://lists.suckless.org/dev/1811/33033.html) of [Michael Forney](https://github.com/michaelforney).

Best regards,
Daniel

```diff
diff -urN netbsd-curses.orig/libterminfo/names.awk netbsd-curses/libterminfo/names.awk
--- netbsd-curses.orig/libterminfo/names.awk	Thu Jan  1 00:00:00 1970
+++ netbsd-curses/libterminfo/names.awk	Mon Nov 26 15:26:54 2018
@@ -0,0 +1,21 @@
+/TICODE_[a-z]+,/ {
+	names[++numnames] = substr($1, 8, length($1) - 8)
+}
+
+/^#define t_[a-z]+(t)/ {
+	fnames[++numfnames] = substr($2, 3, length($2) - 5)
+}
+
+END {
+	print "\nconst char *const strnames[] = {"
+	for (i = 1; i <= numnames; ++i)
+		print("\t\"" names[i] "\",")
+	print "\t(void *)0"
+	print "};"
+
+	print "\nconst char *const strfnames[] = {"
+	for (i = 1; i <= numfnames; ++i)
+		print("\t\"" fnames[i] "\",")
+	print "\t(void *)0"
+	print "};"
+}
diff -urN netbsd-curses.orig/libterminfo/term.h netbsd-curses/libterminfo/term.h
--- netbsd-curses.orig/libterminfo/term.h	Mon Nov 26 15:17:58 2018
+++ netbsd-curses/libterminfo/term.h	Mon Nov 26 15:26:00 2018
@@ -1944,6 +1944,8 @@
 #endif
 
 extern TERMINAL *cur_term;
+extern const char *const strfnames[];
+extern const char *const strnames[];
 
 /* setup functions */
 int		setupterm(const char *, int, int *);
diff -urN netbsd-curses.orig/GNUmakefile netbsd-curses/GNUmakefile
--- netbsd-curses.orig/GNUmakefile	Mon Nov 26 16:06:47 2018
+++ netbsd-curses/GNUmakefile	Mon Nov 26 16:08:49 2018
@@ -67,6 +67,7 @@
 TI_SRCS+=libterminfo/compile.c libterminfo/hash.c
 TI_SRCS+=libterminfo/cdbr.c
 TI_SRCS+=libterminfo/mi_vector_hash.c
+TI_SRCS+=libterminfo/names.c
 # Build in termcap emulation
 TI_SRCS+=libterminfo/termcap.c
 TI_LIBA=libterminfo/libterminfo.a
@@ -74,6 +75,9 @@
 TI_OBJS=$(TI_SRCS:.c=.o)
 TI_LOBJS=$(TI_SRCS:.c=.lo)
 TI_MAN =$(sort $(wildcard libterminfo/*.3))
+
+libterminfo/names.c: libterminfo/term.h
+	cat $^ | awk -f libterminfo/names.awk > $@
 
 libterminfo/term.o: CPPFLAGS+=-DINSTALL_PREFIX=\"$(PREFIX)\"
 libterminfo/term.lo: CPPFLAGS+=-DINSTALL_PREFIX=\"$(PREFIX)\"
diff -urN netbsd-curses.orig/libterminfo/GNUmakefile netbsd-curses/libterminfo/GNUmakefile
--- netbsd-curses.orig/libterminfo/GNUmakefile	Mon Nov 26 15:17:58 2018
+++ netbsd-curses/libterminfo/GNUmakefile	Mon Nov 26 15:23:01 2018
@@ -12,6 +12,7 @@
 SRCS+=		compile.c hash.c
 SRCS+=		cdbr.c
 SRCS+=		mi_vector_hash.c
+SRCS+=		names.c
 
 INCS=		term.h
 INCSDIR=	/usr/include
@@ -99,6 +100,9 @@
 
 term.c: compiled_terms.c
 termcap.c: termcap_hash.c
+
+names.c: term.h
+	cat $^ | awk -f names.awk > $@
 
 libterminfo.a: $(OBJS)
 	ar cru $@ $^

```

**Comment by rofl0r** [comment] 2018-11-26 18:51
thanks for your patch. i've forwarded it to roy smarples, the main author of the upstream sources.

i've seen through the site you linked that you sent a mail to https://www.openwall.com/lists/sabotage/2018/11/23/1 . i just want to let you know that that mailing list is currently unmaintained.

small nitpick: the code for the clean target is missing in the Makefile, but i'll tackle that after this gets merged upstream.

**Comment by silentbits** [comment] 2018-11-26 19:13
(BSD)Makefile: Yes, but I assumed that the (linux) port is based on your code in [netbsd-curses/GNUMakefile](https://github.com/sabotage-linux/netbsd-curses/blob/master/GNUmakefile). GNU make prefers GNUMakefile if it exists.

btw. we plan to use [vis editor](https://github.com/martanne/vis) with netbsd-curses, but we have a problem with that.

[https://lists.suckless.org/dev/1811/33034.html](https://lists.suckless.org/dev/1811/33034.html)

**Comment by rofl0r** [comment] 2018-11-26 19:16
just out of curiosity, what makes `vis` so desirable ? sounds like just another vim to me.
and it seems to be the only program using these odd unibilium/libtermkey libs authored by the guys of `##perl`.

**Comment by silentbits** [comment] 2018-11-26 19:41
> @rofl0r just out of curiosity, what makes vis so desirable ? 

statically linked + lua + netbsd-curses + all lexers, plugins and themes (full installation):
```
# du -hs /tmp/ports/vis/image/         
1.8M	/tmp/ports/vis/image
# ls -lh /tmp/ports/vis/image/usr/bin/vis                                                    
-r-xr-xr-x    1 root     bin        639.4k Nov 26 17:36 /tmp/ports/vis/image/usr/bin/vis
```
> @rofl0r sounds like just another vim to me.

[https://github.com/martanne/vis/wiki/Differences-from-Vi(m)](https://github.com/martanne/vis/wiki/Differences-from-Vi(m)
)

> @rofl0r and it seems to be the only program using these odd unibilium/libtermkey libs authored by the guys of ##perl.

unibilium is optional - I want to use netbsd-curses instead.

btw. statically linked neat(vi)
```
# ls -lh /usr/bin/vi
-r-xr-xr-x    2 root     root       90.8K Nov 11 21:49 /usr/bin/vi
```

**Comment by michaelforney** [comment] 2018-11-26 19:55
After I posted that awk snippet, I realized it isn't quite correct. It matches too much (not only from `TISTRS` enum), and doesn't match the last item in the enum (no trailing comma).

Some more work will need to go into `names.awk` if it is to be merged upstream.

**Comment by silentbits** [comment] 2018-11-26 20:14
> @michaelforney: and doesn't match the last item in the enum (no trailing comma).

Yes, I also had doubts whether this is correct.
```diff
diff -urN netbsd-curses.orig/libterminfo/names.awk netbsd-curses/libterminfo/names.awk
--- netbsd-curses.orig/libterminfo/names.awk	Thu Jan  1 00:00:00 1970
+++ netbsd-curses/libterminfo/names.awk	Mon Nov 26 15:26:54 2018
@@ -0,0 +1,21 @@
+/TICODE_[a-z]+,/ {
+	names[++numnames] = substr($1, 8, length($1) - 8)
+}
+
+/^#define t_[a-z]+(t)/ {
+	fnames[++numfnames] = substr($2, 3, length($2) - 5)
+}
+
+END {
+	print "\nconst char *const strnames[] = {"
+	for (i = 1; i <= numnames; ++i)
+		print("\t\"" names[i] "\",")
+	print "\t(void *)0,"
+	print "};"
+
+	print "\nconst char *const strfnames[] = {"
+	for (i = 1; i <= numfnames; ++i)
+		print("\t\"" fnames[i] "\",")
+	print "\t(void *)0,"
+	print "};"
+}
```

**Comment by silentbits** [comment] 2018-11-26 20:16
btw. MKnames from ncurses
[https://github.com/mirror/ncurses/blob/master/ncurses/tinfo/MKnames.awk](https://github.com/mirror/ncurses/blob/master/ncurses/tinfo/MKnames.awk)

**Comment by rsmarples** [comment] 2018-11-27 14:45
I don't see the point of returning a list of names terminfo provides like that.
You can work out if a terminfo name exists at compile time and runtime like so:

```
/* runtime */
char *kdown1 = tigetstr("kcud1");
if (kdown1 == (char *)-1)
    kdown1 = NULL;

/* compile time */
#ifdef key_down
const char *kdown1 = key_down;
#else
const char *kdown1 = NULL;
#endif
```

**Comment by rsmarples** [comment] 2018-11-27 16:35
@silentbits happy to be ncurses compatible when it makes sense, but this doesn't make sense to me when you can get the same functionality from portable functions and variables.

libtermkey was deprecated  upstream over 5 years ago, they should really look into using something more .... portable.

I'll ask other NetBSD terminfo/curses devs and see if they want to consider this non standard function.

**Comment by rsmarples** [comment] 2018-11-27 17:00
In the meantime, you can get a list of terminfo names by grabbing the output of this command:
```
infocmp -1 | sed -n -e '1,2d' -e 's/[[:space:]]*\([^,=#]*\).*$/\1/p'
```

That works with NetBSD curses and ncurses.
As it's only used when libtermkey fires up, any performance hit would be negligable.

**Comment by silentbits** [comment] 2018-11-27 17:51
@rsmarples: I agree with your opinion. The problem is deprecated libtermkey and should be replaced (or removed). I will try to extract the minimum necessary code from libtermkey, and then check what will be necessary to replace this functionality directly in vis. Thank you for your help and advice.

**Comment by nbuwe** [comment] 2018-11-28 15:39
I agree with @rsmarples.  I would also note that after getting the capability name the code calls [`funcname2keysym`](https://github.com/o11c/libtermkey/blob/7909067ac05e885211dafa255da0526543bb87bf/driver-ti.c#L221-L222) anyway and ignores the capability if it doesn't know about it.  So I'd say iterating over `strfnames[]` just to use only the name the code already knows about is a very roundabout way to do what the code is trying to do.

**Comment by michaelforney** [comment] 2020-05-16 09:31
It looks like as of libtermkey-0.21, it no longer uses `strnames` and `strfnames`, so I think this issue can be closed.

**Closed** 2020-07-14 11:22 UTC
